apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
stringData:
  config.json: |
    {
     "auths": {
		"arti-jfrog-integrations.apps.ocp-dev01.lab.eng.tlv2.redhat.com": {
			"auth": "base64(username:password)"
		}
	}
  }


